#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKTREE_ROOT="${WARCRAFT_WORKTREE_ROOT_OVERRIDE:-$ROOT_DIR}"
WORKTREE_META_DIR="${WARCRAFT_WORKTREE_META_DIR:-$WORKTREE_ROOT/.warcraft}"
RUNTIME_ROOT="${WARCRAFT_WORKTREE_RUNTIME_DIR:-$WORKTREE_META_DIR/runtime}"
ENV_PATH="${WARCRAFT_WORKTREE_ENV_PATH:-$WORKTREE_META_DIR/worktree-env.sh}"

mkdir -p "$WORKTREE_META_DIR"

cat > "$ENV_PATH" <<EOF
#!/usr/bin/env bash
# Generated by scripts/setup_worktree_env.sh
# This keeps branch-local runtime data and cache inside the worktree while
# leaving shared config/state in the host-level XDG roots for seamless auth reuse.

export WARCRAFT_WORKTREE_ROOT="$WORKTREE_ROOT"
export WARCRAFT_WORKTREE_RUNTIME_DIR="$RUNTIME_ROOT"

case ":\${PATH:-}:" in
  *:"$WORKTREE_ROOT/.venv/bin":*)
    ;;
  *)
    export PATH="$WORKTREE_ROOT/.venv/bin:\$PATH"
    ;;
esac
EOF

chmod +x "$ENV_PATH"

echo "Wrote worktree env: $ENV_PATH"
echo "Source with: source \"$ENV_PATH\""
